### PR TITLE
Cors and homepage

### PR DESCRIPTION
**Pull request by ynaumov**
JFYI. This is a currently running version of the Kafka-WebSocket relay.

### CODE REVIEW

**Review by shuston — CHANGES_REQUESTED** [review]
Thank you, Yury. I would like the code to be cleaned up and documented a little bit - I left some notes in the review. Since we are going to be using this for a while it should be neatened up.

**Comment by ynaumov** [comment]
Steve, thank you for the review! I've cleaned up the code, added a small description into the README file and renamed the package . Could you please review again?

**Review by shuston — CHANGES_REQUESTED** [review]
Good work, Yury - thank you.
Could you please change the package name? Having it a subpackage from the message library may be confusing.
I think com.collins.railwaynet.relay would be good.

**Comment by ynaumov** [comment]
Sure! I've changed the package name.

**Review by shuston — APPROVED** [review]
Thank you, Yury - looks good.

**Pull request merged**
